- name: install and start nginx
  hosts: catalogue
  become: yes
  tasks:
  - name: install nginx
    ansible.builtin.package:
      name: nginx
      state: present

  - name: start nginx
    ansible.buitin.service:
      name: nginx
      state: started
      enabled: yes
